### ISSUE TITLE
Getting 404s running the sample code

### ISSUE THREAD

**Issue by AaronRobinson** [ISNIT0/RightMove-Scraper#1]
The code is using 

http://api.rightmove.co.uk/api/sale/find?index=0&sortType=2&numberOfPropertiesRequested=0&locationIdentifier=OUTCODE%5EHP13&apiApplication=IPAD

Is the http://api.rightmove.co.uk/api something that was previously available from rightmove?

**Comment by ISNIT0** [comment]
Good question, I should probably write some documentation out.

The outcode that goes in the URL isn't your normal format: HP13
Rightmove seem to have their own proprietary mappings: http://stackoverflow.com/questions/23067005/rightmove-outcode-url-parameter-for-scraper

E.g:
![image](https://cloud.githubusercontent.com/assets/5173131/14557997/e3ad50dc-02f7-11e6-9245-bef7ce58f041.png)
becomes:
![image](https://cloud.githubusercontent.com/assets/5173131/14558010/f9fcf16c-02f7-11e6-9539-e68b32457ea3.png)

Try using this url instead: http://api.rightmove.co.uk/api/sale/find?index=0&sortType=2&numberOfPropertiesRequested=0&locationIdentifier=OUTCODE%5E1081&apiApplication=IPAD

If you look at https://github.com/ISNIT0/RightMove-Scraper/blob/master/RightMoveScraper.js

You can see that on startup, we run:

``` javascript
var outcodes = {};
db.rightmoveCodes.find({}, function(err, docs){
  docs.map(function(val, index){
    outcodes[val.outcode]=val.locationIdent;
  });
});
```

This reads from a mongodb collection created by https://github.com/ISNIT0/Rightmove-Scrapers/tree/master/rightmoveOutcodeScraper

I've been meaning to create a proper repo with all of this stuff in and with proper documentation.
If you're interested in helping we could jump on some VOIP tool and chat about it?

**Comment by ISNIT0** [comment]
@AaronRobinson Did this help at all?

**Comment by jwasinski** [comment]
@ISNIT0 It would be helpful to get a json file with the Postcode > Outcode transposition.

**Comment by ISNIT0** [comment]
@jwasinski I'll see what I can do, but it is pretty huge

**Comment by ISNIT0** [comment]
@jwasinski  Should be fixed now - you'll nee to get hold of the data here:https://github.com/ISNIT0/rightmove-outcode-scraper/blob/master/README.md

**Comment by ISNIT0** [comment]
@AaronRobinson would you mind shooting me an email please: joseph.reeve (AT) googlemail.com
