### ISSUE TITLE
Documentation on how to run

### ISSUE THREAD

**Issue by bindas12** [ISNIT0/RightMove-Scraper#2]
Hi,
Thanks for sharing this.
Is there any way of you sharing some step by step instructions ? A dummys guide if possible ? 

Thanks
Kris

**Comment by ISNIT0** [comment]
Hi Kris,
Would you mind shooting me an email at joseph.reeve (AT) googlemail.com

**Comment by pyudroi** [comment]
Hi, thanks for sharing this. 

> How to fetch next thousand results from scrape - currently it is getting first thousand results.
> How to fetch based on minimum price and max price

Thank you,
